spring.application.name=backend

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/fabjava
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update

springdoc.swagger-ui.with-credentials=true

minio.url:http://localhost:9000
minio.access-key:admin
minio.secret-key:12345678
minio.bucket:fab-media

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB